# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]
    name: CI
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go build cmd/main.go
      - uses: actions/checkout@v2
      - name: Go Vet
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go vet ./...

